# Production release workflow

name: Production Release Workflow

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  # Flutter Client Application
  app:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    steps:
      - uses: actions/checkout@v2

  # NodeJs Api
  api:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
      - uses: actions/checkout@v2

  # PostgreSql Database
  db:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api/data

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          npm install
          npx sequelize-cli db:migrate --env prod
