# Pre-release workflow

name: Pre-Release Workflow

on:
  pull_request:
    branches: [ pre ]

  workflow_dispatch:

jobs:

  # Flutter Client Application
  app:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    steps:
      - uses: actions/checkout@v2

  # NodeJs Api
  api:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
      - uses: actions/checkout@v2

  # PostgreSql Database
  db:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api/data

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        env:
          DB_PRE_HOST: ${{ secrets.DB_PRE_HOST }}
          DB_PRE_NAME: ${{ secrets.DB_PRE_NAME }}
          DB_PRE_USER: ${{ secrets.DB_PRE_USER }}
          DB_PRE_PASSWORD: ${{ secrets.DB_PRE_PASSWORD }}
        run: |
          npm install
          npx sequelize-cli db:migrate --env pre

